version: '3.9'
services:
  server:
    image: rpi-server
    build: ./server
    environment:
      - MONGODB_URL=${MONGODB_URL}
    volumes:
      - type: bind
        source: ./server
        target: /rpi-hex-control
    ports:
      - 9000:9000
    devices:
      - "/dev/mem:/dev/mem"
    privileged: true
volumes:
  dev: