title: Hexagon LED Project
description: A simple Raspberry Pi controlled, LED planter

repository: dakerr/rpi-hex-control
# destination: ./docs/_site
baseurl: /rpi-hex-control

theme: jekyll-theme-material-docs

main_nav:
  - title: Get Started
    url: /getting-started
  
content_table:
  - title: DEV Environment
  - title: Dependency Management
  - title: Project Organization
  - title: API and Web Server
    links:
      - title: get Mode
      - title: set Mode
      - title: set Color
      - title: set Hex Color
  - title: Hardware
  - title: Construction